declare const process: {
  env: {
    EXPO_PUBLIC_API_URL?: string;
    EXPO_PUBLIC_WEB_URL?: string;
    EXPO_PUBLIC_CONTACT_EMAIL?: string;
    EXPO_PUBLIC_DONATION_BANK_BENEFICIARY?: string;
    EXPO_PUBLIC_DONATION_BANK_IBAN?: string;
    EXPO_PUBLIC_DONATION_BANK_BIC?: string;
    EXPO_PUBLIC_DONATION_BANK_NAME?: string;
    EXPO_PUBLIC_DONATION_BANK_ADDRESS?: string;
    EXPO_PUBLIC_DONATION_BANK_CORRESPONDENT_BIC?: string;
    EXPO_PUBLIC_DONATION_BANK_REFERENCE?: string;
  };
};
